# Generated by Django 5.1.3 on 2024-11-14 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(unique=True, verbose_name="ID Telegram"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
            ],
            options={
                "verbose_name": "TG-Пользователь",
                "verbose_name_plural": "TG-Пользователи",
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "telegramuser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.telegramuser",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "phone_number",
                    models.CharField(max_length=255, verbose_name="Номер телефона"),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="Email")),
                (
                    "referal_link",
                    models.CharField(max_length=255, verbose_name="Реферальная ссылка"),
                ),
            ],
            options={
                "verbose_name": "Партнер",
                "verbose_name_plural": "Партнеры",
            },
            bases=("users.telegramuser",),
        ),
    ]
