# Generated by Django 5.1.3 on 2024-11-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Баланс"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="partner",
            name="proccess_type",
            field=models.CharField(
                choices=[
                    ("funnel_agency", "Воронка 1 (агент)"),
                    ("funnel_cpa", "Воронка 2 (CPA)"),
                    ("referral", "Реферальная"),
                ],
                default="funnel_agency",
                max_length=255,
                verbose_name="Тип воронки",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="referal_idx",
            field=models.CharField(
                default=1, max_length=10, unique=True, verbose_name="Реферальный индекс"
            ),
            preserve_default=False,
        ),
    ]
