# Generated by Django 5.1.3 on 2024-11-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_partner_balance_partner_proccess_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Баланс",
            ),
        ),
    ]
