# Generated by Django 5.1.3 on 2024-11-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_partner_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="ID Telegram"
            ),
        ),
    ]
