# Generated by Django 5.1.3 on 2024-11-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_telegramuser_telegram_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="referal_idx",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Реферальный индекс"
            ),
        ),
    ]
