# Generated by Django 5.1.3 on 2024-11-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_partner_referal_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="referal_link",
        ),
    ]
