# Generated by Django 5.1.3 on 2024-11-14 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processingapplication",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="processingapplication",
            name="id",
        ),
        migrations.AddField(
            model_name="processingapplication",
            name="telegramuser_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="users.telegramuser",
            ),
            preserve_default=False,
        ),
    ]
