services:
  web:
    build: .
    command: uvicorn adminpanel.asgi:application --host 0.0.0.0 --port 8000 --forwarded-allow-ips "*" --proxy-headers --workers 4
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env_docker
    environment:
      RUN_MIGRATIONS: "true"
      LOAD_FIXTURES: "true"

  bot:
    build: .
    command: python manage.py runbot
    depends_on:
      - db
    env_file: .env_docker

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_USER=${DB_USER}
    env_file:
      - .env_docker
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db:
