services:
  web:
    build: .
    command: uvicorn adminpanel.asgi:application --host 0.0.0.0 --port 8000 --forwarded-allow-ips "*" --proxy-headers --workers 4
    volumes:
      - ./media:/app/media
    depends_on:
      - db
    env_file: .env_docker

  bot:
    build: .
    command: python manage.py runbot
    volumes:
      - ./media:/app/media
    depends_on:
      - db
    env_file: .env_docker

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      # - "443:443"  # пока не слушаем 443
    depends_on:
      - web
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    restart:
      always
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_USER=${DB_USER}
    env_file:
      - .env_docker
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis

  celery:
    build: .
    command: celery -A adminpanel worker --loglevel=info
    volumes:
      - ./media:/app/media
    depends_on:
      - db
      - redis
    env_file: .env_docker

  celery-beat:
    build: .
    command: celery -A adminpanel beat --loglevel=info
    depends_on:
      - db
      - redis
    env_file: .env_docker

volumes:
  db:
  media:
