# Generated by Django 5.1.3 on 2024-11-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vacancy",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название вакансии"
            ),
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="city",
        ),
    ]
