# Generated by Django 5.1.3 on 2024-11-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="conditions",
            field=models.TextField(
                blank=True, null=True, verbose_name="Условия"
            ),
        ),
    ]
