# Generated by Django 5.1.3 on 2024-11-25 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="ID Telegram"
                    ),
                ),
                (
                    "tg_username",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="TG Username",
                    ),
                ),
                (
                    "is_partner",
                    models.BooleanField(default=False, verbose_name="Партнёр"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Подтверждён"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="users.telegramuser",
                        verbose_name="Пригласил",
                    ),
                ),
            ],
            options={
                "verbose_name": "TG-Пользователь",
                "verbose_name_plural": "TG-Пользователи",
            },
        ),
        migrations.CreateModel(
            name="TelegramChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название канала"),
                ),
                ("chat_id", models.CharField(max_length=255, verbose_name="ID канала")),
            ],
            options={
                "verbose_name": "Канал",
                "verbose_name_plural": "Каналы",
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="partner_profile",
                        serialize=False,
                        to="users.telegramuser",
                        verbose_name="Телеграм-пользователь",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "phone_number",
                    models.CharField(max_length=255, verbose_name="Номер телефона"),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="Email")),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Баланс",
                    ),
                ),
                (
                    "proccess_type",
                    models.CharField(
                        choices=[
                            ("funnel_agency", "Агент"),
                            ("funnel_cpa", "CPA"),
                            ("referral", "Реферальная"),
                        ],
                        default="funnel_agency",
                        max_length=255,
                        verbose_name="Тип воронки",
                    ),
                ),
                (
                    "referal_idx",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Реферальный индекс"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Партнер",
                "verbose_name_plural": "Партнеры",
            },
        ),
    ]
