# Generated by Django 5.1.3 on 2024-11-19 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название канала"
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(max_length=255, verbose_name="ID канала"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="partner",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="partner_profile",
                serialize=False,
                to="users.telegramuser",
                verbose_name="Телеграм-пользователь",
            ),
        ),
    ]
