# Generated by Django 5.1.3 on 2024-11-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_telegramchannel_alter_partner_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telegramchannel",
            options={"verbose_name": "Канал", "verbose_name_plural": "Каналы"},
        ),
    ]
