# Generated by Django 5.1.3 on 2024-11-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_partner_proccess_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="proccess_type",
            field=models.CharField(
                choices=[
                    ("funnel_agency", "Агент"),
                    ("funnel_cpa", "CPA"),
                    ("referral", "Реферальная"),
                ],
                default="funnel_agency",
                max_length=255,
                verbose_name="Тип воронки",
            ),
        ),
    ]
