# Generated by Django 5.1.3 on 2024-11-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_partner_proccess_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="invited_by_partner",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="От партнёра"
            ),
        ),
    ]
