# Generated by Django 5.1.3 on 2024-11-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingapplication",
            name="bitrix_lead_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
