# Generated by Django 5.1.3 on 2024-11-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingapplication",
            name="car_tonnage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("156", "0,5 - тонн (Легковое авто)"),
                    ("158", "до 1 тонны (Каблук или микроавтобус)"),
                    ("160", "1,5 тонны (Газели и др.)"),
                    ("1106", "Штат (авто компании)"),
                    ("1284", "Несколько машин (ИП,ООО и др.)"),
                ],
                max_length=20,
                null=True,
                verbose_name="Грузоподъемность",
            ),
        ),
        migrations.AlterField(
            model_name="processingapplication",
            name="tax_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("152", "Самозанятый"),
                    ("150", "Индивидуальный предприниматель"),
                    ("656", "Не оформлен"),
                    ("1212", "Штат (на авто компании)"),
                    ("1308", "Юридическое Лицо (все кроме ИП)"),
                ],
                max_length=20,
                null=True,
                verbose_name="Статус налогоплательщика",
            ),
        ),
    ]
