# Generated by Django 5.1.3 on 2024-11-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applications",
            "0003_alter_processingapplication_car_tonnage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="processingapplication",
            name="is_finalized",
            field=models.BooleanField(
                default=False, verbose_name="Финализирована"
            ),
        ),
    ]
