# Generated by Django 5.1.3 on 2024-11-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_processingapplication_is_finalized"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingapplication",
            name="car_tonnage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0.5", "до 0.5 т"),
                    ("1", "до 1 т"),
                    ("1.5", "до 1.5 т"),
                    ("1.5+", "от 1.5 т"),
                    ("Нет", "Нет машины (нужна аренда)"),
                ],
                max_length=20,
                null=True,
                verbose_name="Грузоподъемность",
            ),
        ),
        migrations.AlterField(
            model_name="processingapplication",
            name="tax_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("СМЗ", "Самозанятый"),
                    ("ИП", "Индивидуальный предприниматель"),
                    ("Физ", "Физическое лицо"),
                ],
                max_length=20,
                null=True,
                verbose_name="Статус налогоплательщика",
            ),
        ),
    ]
