# Generated by Django 5.1.3 on 2024-11-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applications",
            "0005_alter_processingapplication_car_tonnage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="processingapplication",
            name="reward_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=1000,
                max_digits=10,
                verbose_name="Сумма вознаграждения",
            ),
        ),
    ]
