# Generated by Django 5.1.3 on 2024-11-22 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_processingapplication_reward_amount"),
        ("users", "0003_alter_telegramchannel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingapplication",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.partner",
                verbose_name="Партнер",
            ),
        ),
    ]
