# Generated by Django 5.1.3 on 2024-11-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="btx_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="ID города в Битриксе"
            ),
        ),
    ]
